---
title: "step 1: arrange Biigle annotations"
author: "Your Name"
date: "Today's Date"
format:
  html:
    toc: true
    number-sections: true
---

## Setup

Before beginning, we will load necessary libraries and set symbolic pathways 

```{r}

library(tidyverse)

# setting the current working directory as base path - you can customize it to your needs   
getwd() -> wd
# delete the "code" part of the pathway so that the rest of the path are not relative to the code directory
wd <- str_remove(wd, "/code") 

# set the working directory to the directory above "code" - it will only change anything if you have set a custom wd
# setwd(wd) 

# list the csv tables and print their names

# exclude the "arranged" pattern - it will be used in files geerated by this code 
list.files(paste0( wd,"/annotations"), pattern = ".csv$" ) %>% 
# exclude the "arranged" pattern - it will be used in files geerated by this code
str_subset(pattern = "arranged", negate = T)  %>% 
  paste(., collapse = "\n - ") %>% 
  paste0("Avialable annotation CSV tables: \n - ",.,"\n") %>% cat()

 

```

### Load data

```{r}

generic_annotation_file <-  "generic_annotation.csv"

read_csv( paste0(wd,"./annotations/",generic_annotation_file )  ) -> All_annotations

print(paste0("loading annotation file: ", generic_annotation_file, "  with ", nrow(All_annotations)  ) )




```

### sort

Sorting annotations chronically by time in video, represented by chronically order of "frames" column

```{r}

All_annotations %>%
  # make frame to numerical value by removing the brackets, replacing "null" with "0", 
  mutate(frame_new =    frames %>% str_sub( 2, -2)  %>% 
           str_replace("null",replacement = "0") %>% 
           str_split(pattern = ",") %>%
           # splitting by comma and taking the first value (in case there are multiple values separated by commas) - Biigle does this with tracked annotations 
           map_vec(~head(.x,1) %>% as.numeric)) -> All_annotations

# sort per image frame, so in order of appearence in the video
All_annotations %>%  arrange(frame_new) -> All_annotations



```

### View the filename and video time 

```{r}

if(All_annotations %>% distinct(video_filename) %>% nrow() > 1 ) {
  print("there are multiple video filenames in the annotation file, are you sure they are continuous?")
} else {
  print(paste0("the video filename in the annotation file is: ", All_annotations %>% distinct(video_filename) %>% pull() ) )
}

# time difference between first and last annotations in seconds
time_diff <- All_annotations %>% slice(n()) %>% pull(frame_new) - All_annotations %>% slice(1) %>% pull(frame_new)
print(paste0("time difference between first and last annotation: ", time_diff %>%  round(), " seconds") )
 

```
### look for a laser label 

```{r}

All_annotations %>% filter( grepl("laser", label_name, ignore.case = T) ) %>% 
  distinct(label_name) %>% pull() -> laser_label 

if(length(laser_label) == 0 ) { 
  print("no laser label found in the annotation file, please check your annotation file and make sure there is a label that contains the word 'laser' (case insensitive)")
} else {
  print(paste0("the laser label in the annotation file is: ", laser_label ) )
}

```

### export

```{r}

# export re-arranged annotations 
write_csv(All_annotations, paste0(wd,"/annotations/arranged_annotation_file.csv"   )  )

paste0( "exporting arranged annotation file: \n",  wd,"/annotations/arranged_annotation_file.csv \n"   )  %>% cat()

```
